{
    "extends": [
    "stylelint-config-standard",
    "stylelint-config-prettier",
    "stylelint-prettier/recommended",
  ],
    "rules": {
        "selector-class-pattern": "^[a-z]([-]?[a-z0-9]+)*(__[a-z0-9]([-]?[a-z0-9]+)*)?(_[a-z0-9]([-]?[a-z0-9]+)*)?$",
        "font-family-no-missing-generic-family-keyword": null
    }
}